project_name: terraform-provider-slack

builds:
  - binary: terraform-provider-slack
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-mod=vendor
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -extldflags '-static'

archives:
  - format: binary
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    files:
      - nothing.*

release:
  github:
    owner: janitors
    name: terraform-provider-slack
