dist: xenial
sudo: required
language: go

git:
  depth: 1

env:
  global:
    GO111MODULE=on

install:
  - make tools

script:
  - make lint
  - make test

branches:
  only:
    - master
    - /^v.*$/

deploy:
  - provider: script
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_OS_NAME = linux
